version: 2

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.Revision={{.ShortCommit}}
      - -extldflags -static
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm64
    binary: "{{ .ProjectName }}"
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}_SHA256SUMS"
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--local-user"
      - "E37EC0B895A9AC27DC4919AB96CEB4B93D86849D"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
# release:
#   for debug
#   draft: true
changelog:
  disable: false
